### ISSUE TITLE
FileSystemNotFoundException

### ISSUE THREAD

**Issue by wjatekTest** [jshaptic/jshint-javaport#1]
Hi
I use JSHint in my Maven project. Java 1.8.0_201.
When I call method lint() there is ExceptionInInitializerError caused by FileSystemNotFoundException.
Here is my call stack:
`Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jshint.Lexer.scanIdentifier(Lexer.java:831)
	at org.jshint.Lexer.next(Lexer.java:2113)
	at org.jshint.Lexer.token(Lexer.java:2318)
	at org.jshint.JSHint.advance(JSHint.java:1034)
	at org.jshint.JSHint.advance(JSHint.java:953)
	at org.jshint.JSHint.expression(JSHint.java:1144)
	at org.jshint.JSHint.statement(JSHint.java:2570)
	at org.jshint.JSHint.statements(JSHint.java:2635)
	at org.jshint.JSHint.run(JSHint.java:8303)
	at org.jshint.JSHint.lint(JSHint.java:8090)
	at org.jshint.JSHint.lint(JSHint.java:8054)
	at main.main(main.java:8)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at org.jshint.data.ES5IdentifierNames.<clinit>(ES5IdentifierNames.java:21)
	... 12 more`

**Comment by jshaptic** [comment]
Hi
Thanks for reporting this issue! What a lame error from my side ) haven't tested package outside of my project..

I have fixed this bug in the new version 2.10.1.1, you can test it already.

**Comment by wjatekTest** [comment]
Thanks for the quick response!
